contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #rnasequence channel"
    url: https://nfcore.slack.com/channels/rnasequence
    about: Discussion about the nf-core/rnasequence pipeline
